services:
  selenium-chrome:
    # Use official Selenium with Chrome
    image: selenium/standalone-chrome
    # Name of the Selenium container
    container_name: selenium
    # Expose Selenium WebDriver port (host:container)
    ports:
      - "4444:4444"
    # Increase shared memory size to avoid Chrome crashes (esp. in headless mode)
    shm_size: "2g"

  selenium-firefox:
      # Use official Selenium image with Firefox
      image: selenium/standalone-firefox:latest
      container_name: selenium-firefox
      # Map internal port 4444 to host port 4445 to avoid conflicts with Chrome
      ports:
        - "4445:4444"
      shm_size: "2g"

  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_DB: hotel_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      # Persist database data outside the container
      - postgres_data:/var/lib/postgresql/data
      # Initialize database with scripts from local folder
      - ./src/db:/docker-entrypoint-initdb.d/

  tests:
    # Build Docker image from current directory (uses Dockerfile)
    build: .
    # Name of the container that runs tests
    container_name: tests
    depends_on:
      # Make sure that Selenium containers and the database are started before launching the tests
      - selenium-chrome
      - selenium-firefox
      - db
    environment:
      # Path where test logs will be written inside the container
      LOG_PATH: /app/logs
      # Path where Allure test results will be saved
      ALLURE_RESULTS: /app/allure-results
      # URL for Chrome Remote WebDriver container
      SELENIUM_CHROME_URL: http://selenium-chrome:4444/wd/hub
      # URL for Firefox Remote WebDriver container
      SELENIUM_FIREFOX_URL: http://selenium-firefox:4444/wd/hub

    volumes:
      # Mount current project folder into the container at /app
      - .:/app
      - ./logs:/app/logs
      - ./allure-results:/app/allure-results
     # Set working directory inside the container
    working_dir: /app
    # Entry point — wait for Selenium, then run tests
    command: [ "/app/scripts/wait-for-selenium.sh" ]

    env_file:
      - .env

#Declaring volumes for permanent data storage
volumes:
  postgres_data:
  allure-results:
