name: Restful Booker Platform tests

on:
  push:
    branches:
    - features/add-firefox-support
    - features/A
  pull_request:
    branches:
      - refactor_test_data_db
      - features/A

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: 🐳 Build Docker containers
        run: docker compose build

      - name: 🐳 Check files in container root
        run: docker compose run --rm tests ls -l /

      - name: 🐳 Check wait-for-selenium.sh permissions
        run: docker compose run --rm tests ls -l /app/scripts/wait-for-selenium.sh

      - name: 🐳 Show wait-for-selenium.sh contents
        run: docker compose run --rm tests cat /app/scripts/wait-for-selenium.sh

      - name: 🐳 Run tests with Docker Compose
        run: docker compose run --rm tests pytest --browser=chrome --alluredir=./allure-results/chrome


      - name: 📤 Upload Allure results (Chrome)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-chrome
          path: allure-results/chrome/

      - name: 📤 Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: logs/

      - name: ✅ Success message
        if: success()
        run: echo "✅ Tests passed!"

      - name: ❌ Failure message
        if: failure()
        run: echo "❌ Tests failed!"
