name: Restful Booker Platform tests

on:
  push:
    branches: [ features/docker-ci ]
  pull_request:
    branches: [ features/docker-ci ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: 🐳 Build Docker containers
        run: docker-compose build

      - name: 🐳 Check files in container root
        run: docker-compose run --rm tests ls -l /

      - name: 🐳 Check wait-for-selenium.sh permissions
        run: docker-compose run --rm tests ls -l /wait-for-selenium.sh

      - name: 🐳 Show wait-for-selenium.sh contents
        run: docker-compose run --rm tests cat /wait-for-selenium.sh

      - name: 🐳 Run tests with Docker Compose
        run: docker-compose up --build --abort-on-container-exit

      - name: 📤 Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: logs/  # Папка с логами на хосте

      - name: ✅ Success message
        if: success()
        run: echo "✅ Tests passed!"

      - name: ❌ Failure message
        if: failure()
        run: echo "❌ Tests failed!"
